name: mytaxesinaction
favicon: null
layout_spectrum: 0.04192565055564046
typography_spectrum: 0.9171865538228303
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6820550886914134
  lightness: 0.6609223482664675
  saturation: 0.5606272236909717
  rhythmicContrast: 0.21757440362125635
purpose: []
